### ISSUE TITLE
Order By's DESC/ASC not working

### ISSUE THREAD

**Issue by VR-Architect** [G4brym/workers-qb#12]
FYI, I have not been able to get the DESC/ASC command to work in plan Cloudflare. I added this library and noticed the issue. The result set is the same order for both DESC and ASC. 

I tried it with OrderTypes and the 'ASC' string. I believe there may be a bug in the Cloudflare side though?

**Comment by G4brym** [comment]
Hey @VR-Architect that appears to have been an issue on Cloudflare side, can you try again?
