### ISSUE TITLE
Bulk insert/update we need it 

### ISSUE THREAD

**Issue by hanumanjiblog** [G4brym/workers-qb#13]
Bulk insert/update we need it please update the package

**Comment by rupamking1** [comment]
This feature is most important, please try to implement it

**Comment by G4brym** [comment]
I will try to make it this week 🙂

**Comment by G4brym** [comment]
I've just added bulk insert in the latest release

**Comment by rupamking1** [comment]
@G4brym Awesome ✨

**Comment by rupamking1** [comment]
Please try to implement bulk update, read and delete features. That will complete your bulk module.

**Comment by G4brym** [comment]
You can already do bulk update like this, to update unlimited rows
```js
const updated = await qb.update({
  tableName: 'employees',
  data: {
    role: 'CEO',
    department: 'HQ',
  },
  where: {
    conditions: 'department = ?1',
    params: ['HQ'],
  },
})
```

and do bulk deletes like this, to delete unlimited rows
```js
const updated = await qb.delete({
  tableName: 'employees',
  where: {
    conditions: 'department = ?1',
    params: ['HQ'],
  },
})
```

**Comment by rupamking1** [comment]
@G4brym db.batch may fix it.

**Comment by G4brym** [comment]
Hey @rupamking1 we added support for db.batch in the latest release thanks to @ejyager00
You can see an [example here](https://workers-qb.massadas.com/databases/cloudflare-d1/#batch-queries)
