### ISSUE TITLE
CURRENT_TIMESTAMP is being stored as string rather timestamp

### ISSUE THREAD

**Issue by subhendukundu** [G4brym/workers-qb#14]
```
const tableData = {
      id,
      name,
      user_id: user.id,
      created_at: "CURRENT_TIMESTAMP",
      updated_at: "CURRENT_TIMESTAMP",
};
```
This is being stored as string for created_at and updated_at.

**Comment by G4brym** [comment]
Hey @subhendukundu you can now use the `Raw` class to send raw sql to the query builder checkout the docs here
https://workers-qb.massadas.com/advanced-queries/raw-sql/

**Comment by subhendukundu** [comment]
```
import { Raw } from 'workers-qb'
```
Module '"workers-qb"' has no exported member 'Raw'.

**Comment by G4brym** [comment]
My bad, can you update to the latest version (v0.1.5) and try again
