### ISSUE TITLE
UPSERT [new feature]

### ISSUE THREAD

**Issue by rupamking1** [G4brym/workers-qb#20]
UPSERT is a very useful feature for developers please try to add this feature in workers-qb package.

https://www.sqlite.org/lang_UPSERT.html

**Comment by G4brym** [comment]
I will probably do this in the next minor release 😄

**Comment by G4brym** [comment]
Hey @rupamking1 i've just created a new release (v1.1.0) that adds Upsert support, read the [docs here](https://workers-qb.massadas.com/advanced-queries/upsert/)
