### ISSUE TITLE
Numbered parameters don't work in miniflare

### ISSUE THREAD

**Issue by BraydenGirard** [G4brym/workers-qb#21]
As numbered parameters don't work in miniflare, workers-qb is unable to be used with wrangler dev when run locally. More details on the issue here - https://discord.com/channels/595317990191398933/1080287346794168381

**Comment by G4brym** [comment]
Hey, there's already a bug report for that in the miniflare repo here https://github.com/cloudflare/miniflare/issues/504
There is nothing i can do right now to fix it, my advice is to just run the project without the `--local` flag
