### ISSUE TITLE
0.1.8

### ISSUE THREAD

**Issue by erikhuisman** [G4brym/workers-qb#22]
Hi, 0.1.8 is asking me to turn on `node_compat` when deploying a worker with wrangler even though i only use the D1 bindings.

**Comment by G4brym** [comment]
Hey @erikhuisman thanks for reporting that bug, I wasn't aware of it
I will try to fix it in the upcoming days

**Comment by G4brym** [comment]
Hey @erikhuisman i've released a new version (0.1.9) that fix the problem

**Comment by erikhuisman** [comment]
@G4brym thanks so much!
