### ISSUE TITLE
type definitions missing from v1.0.0

### ISSUE THREAD

**Issue by ejyager00** [G4brym/workers-qb#28]
I'm not familiar with releasing node packages, but it looks like the type definitions are missing from the v1.0.0 release. The v0.1.12 release had the type declaration files in the top level of the `dist` directory. In the v1.0.0 release, it looks like there is a `src` directory that was absent in the v0.1.12 release, and the type declaration files are there instead of in the top level of the `dist` directory.

**Comment by G4brym** [comment]
Hey @ejyager00 i've published a patch release to fix this (v1.0.1)
Thanks for reporting it
