### ISSUE TITLE
JOIN support

### ISSUE THREAD

**Issue by aperture147** [G4brym/workers-qb#4]
Is there anyway to perform JOIN query? If there is, how can I do it?

**Comment by G4brym** [comment]
Hey @aperture147 I will be looking into adding support for this next week 
Thanks for suggesting this 😄

**Comment by G4brym** [comment]
Hey @aperture147   
I've just added support for join clauses in the latest v0.1.13 version
You can read the [docs here](https://workers-qb.massadas.com/advanced-queries/join/)

Let me know if you have any more suggestion

**Comment by subhendukundu** [comment]
`fields: ['role', 'department', 'payroll.salary'],` returning the data in the same level of the object. Would it possible to have the  `salary` key in the `payroll` object?

**Comment by aperture147** [comment]
Thanks for your support! Is there any way to perform joining on multiple table? We can change https://github.com/G4brym/workers-qb/blob/37919e0bf12c475b5cd459a37317af70f09ae4a8/src/Builder.ts#L139 from accepting a single `Join` object to an array of `Join`? Eg:
```typescript
  _join(values?: Array<Join>): string {
    if (!values || !values.length) return ''
    let joinQuery = ''
    values.forEach((item: Join) => {
        const type = value.type ? ` ${value.type}` : ''
        joinQuery += `${type} JOIN ${value.table} ON ${value.on}`
    })

    return joinQuery
  }
```

This is a rough implementation to show the idea, sorry if it does not work.

**Comment by G4brym** [comment]
Hey @subhendukundu that kind of result transformation should be handled in your application, workers-qb is only meant to generate sql queries

**Comment by G4brym** [comment]
Hey @aperture147 I've just added support for multiple joins, checkout the docs here
https://workers-qb.massadas.com/advanced-queries/join/#multiple-joins
