### ISSUE TITLE
How can I mark an insert as only returning one row?

### ISSUE THREAD

**Issue by MrSuttonmann** [G4brym/workers-qb#41]
I'm inserting a row into a table, but the results property that comes back is typed as `<TableType | TableType[]>`.

My IDE gives the following error:

![image](https://github.com/G4brym/workers-qb/assets/7480500/bfc55856-67cf-47dc-a086-544ea37ee186)

I'm guessing just casting the result to the singular is a workaround?

**Comment by G4brym** [comment]
Hey @MrSuttonmann, currently you need to cast the result to singular, because my typescript knowledge is limited and i didn't manage to solve this issue
I will try to solve it again soon, but meanwhile pull requests are well come to solve this 😄

**Comment by G4brym** [comment]
Hello @MrSuttonmann i've just published a new version (v1.2.3) that solves your issue, can you install the update and confirm the fix?
Thanks
