### ISSUE TITLE
alias for main table?

### ISSUE THREAD

**Issue by vickyRathee** [G4brym/workers-qb#42]
How can I use `alias` for main table instead repeating the `employees` in fields array? Because most fields are with same name in joined table (for example: user_id, account_id, uuid, timestamp etc)

I was expecting something like this - 

```
const fetched = await qb
  .fetchAll({
    tableName: 'employees', 
    alias: 'e', 
    fields: ['e.role', 'e.department', 'p.salary'],
    where: {
      conditions: 'e.department = ?1',
      params: ['HR'],
    },
    join: {
      table: 'payroll',
      on: 'p.employee_id = e.id',
      alias: 'p'
    },
  })
  .execute()
```

**Comment by G4brym** [comment]
Hey @vickyRathee currently alias is not "supported" for the main table, but because this is all strings you should be able to work around like this:

```
const fetched = await qb
  .fetchAll({
    tableName: 'employees as e', 
    fields: ['e.role', 'e.department', 'p.salary'],
    where: {
      conditions: 'e.department = ?1',
      params: ['HR'],
    },
    join: {
      table: 'payroll',
      on: 'p.employee_id = e.id',
      alias: 'p'
    },
  })
  .execute()
```

I will provably add alias for main tables soon, but meanwhile you can use the method above

**Comment by vickyRathee** [comment]
@G4brym Thanks, that's helpful
