### ISSUE TITLE
Accessing D1 `meta.rows_written`

### ISSUE THREAD

**Issue by darg-2036** [G4brym/workers-qb#47]
The D1 docs state that a `D1Result` contains a `meta.rows_written` field:
https://developers.cloudflare.com/d1/build-with-d1/d1-client-api/#return-object

The `D1Result` type in this library only exposes `meta.changes`:

https://github.com/G4brym/workers-qb/blob/12daee3c82ac93831d95540c8822dfc33542a2a7/src/databases/d1.ts#L35

Is this an undocumented property of Cloudflare's `D1Result`? Does it behave the same as `rows_written`? If not it would be great if that was exposed as well.

**Comment by G4brym** [comment]
Hey @darg-2036, i've fixed this issue in the latest release (v1.3.1)
On this version you will be able to access all meta fields the same way as the Cloudflare docs `result.meta. rows_written `
